# These are supported funding model platforms

github: # [Izanami-Chan, BelieveInBunny]
ko_fi: # izanamichan
custom: # ["https://github.com/Izanami-Chan/OtakuPlay.Moe/blob/main/donate-crypto.md", iamizanami.com]
